workflows:
  react_build_and_deploy:
    name: "React Build and Beta Test Deploy"
    environment:
      node: "20"
      groups:
        - beta-testers
      vars:
        FIREBASE_PROJECT: "word-guess-game-b8ddf"

    scripts:
      - name: "Install Dependencies"
        script: "npm ci"

      - name: "Build Project"
        script: "npm run build"

    artifacts:
      - build/**

    publishing:
      scripts:
        - name: "Deploy to Firebase Hosting"
          script: |
            echo "Skipping Firebase CLI installation since it already exists..."
            firebase deploy --only hosting --token "$FIREBASE_AUTH_TOKEN" --project $FIREBASE_PROJECT

      email:
        recipients:
          - al-hattami@outlook.com
        notify:
          success: true
          failure: true
        message: |
          🎉 **Build Successful!** 🚀
          
          Your app is now live! You can access it here:
          🔗 **https://word-guess-game-b8ddf.web.app**

          ✅ Deployment Summary:
          - Project: `word-guess-game-b8ddf`
          - Build ID: ${CM_BUILD_ID}
          - Workflow: ${CM_WORKFLOW_ID}
          - Build Duration: ${CM_BUILD_DURATION}
