workflows:
  react_build_and_deploy:
    name: React Build and Deploy
    environment:
      node: 16  # Specify Node.js version
      npm: true # Enable npm

    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Run Tests
        script: npm test
      - name: Build Project
        script: npm run build

    artifacts:
      - build/**
    publishing:
      firebase:
        project_path: build  
        token: $FIREBASE_AUTH_TOKEN
