workflows:
  react_build_and_deploy:
    name: "React Build and Beta Test Deploy"
    environment:
      node: "20"

    scripts:
      - name: "Install Dependencies"
        script: "npm Install"  
      - name: "Build Project"
        script: "npm run build"  

    cache:
      paths:
        - node_modules  

    artifacts:
      - build/** 

    publishing:
      scripts:
        - name: "Deploy to Firebase App Distribution"
          script: |
            firebase appdistribution:distribute --app 1:559732628127:web:845bbd360592c79895e0aa --groups token --token $FIREBASE_AUTH_TOKEN

    publishing:
      email:
        recipients:
      - name@example.com