workflows:
  react_build_and_deploy:
    name: "React Build and Deploy"
    environment:
      node: "20"
    scripts:
      - name: "Install Dependencies"
        script: "npm install"
      - name: "Build Project"
        script: "npm run build"
    artifacts:
      - build/**
    publishing:
      email:
        recipients:
          - Al-hattami@outlook.com
