workflows:
  web-app-workflow:
    name: "Web App Workflow"
    on:
      push:
        branches:
          - "ci-cd-setup" # Ensure this matches your branch name
    scripts:
      - name: "Install Dependencies"
        script: "npm install"
      - name: "Run Tests"
        script: "npm test"
      - name: "Build Project"
        script: "npm run build"
      - name: "Deploy to Firebase"
        script: |
          npm install -g firebase-tools
          firebase deploy --only hosting
