workflows:
  react_build_and_deploy:
    name: "React Build and Deploy"
    environment:
      node: "20"  # Specify Node.js version

    steps:
      - name: "Install Dependencies"
        script: npm ci  # Clean install dependencies

      - name: "Run Lint Check"
        script: npm run lint || echo "Lint warnings/errors detected"

      - name: "Run Tests"
        script: npm test -- --ci --reporters=default

      - name: "Build Project"
        script: npm run build

    artifacts:
      - build/**  # Save build artifacts for deployment or debugging

    publishing:
      email:
        recipients:
          - kengyap@upm.edu.my  # Email for notifications

      scripts:
        - name: "Deploy to Firebase"
          script: firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN
