workflows:
  react_build_and_deploy:
    name: "React Build and Beta Test Deploy"
    environment:
      node: "20"
      groups:
        - group-name

    scripts:
      - name: "Install Dependencies"
        script: "npm ci"
      - name: "Build Project"
        script: "npm run build"  

    artifacts:
      - build/**  

    publishing:
      scripts:
        - name: "Deploy to Firebase App Distribution"
          script: |
            firebase appdistribution:distribute build/app-release.apk \
              --app 1:559732628127:web:845bbd360592c79895e0aa \
              --token "$FIREBASE_AUTH_TOKEN"

      email:
        recipients:
          - al-hattami@outlook.com
