workflows:
  react_build_and_deploy:
    name: "React Build and Deploy"
    environment:
      node: "20"  # Specify Node.js version as a string

    scripts:
      - name: "Install Dependencies"
        script: "npm install"
      - name: "Run Tests"
        script: "npm test"
      - name: "Build Project"
        script: "npm run build"

    artifacts:
      - build/**

    
