workflows:
  react_build_and_deploy:
    name: "React Build and Beta Test Deploy"
    environment:
      node: "20"
      groups:
        - beta-testers

    scripts:
      - name: "Install Dependencies"
        script: "npm ci"

      - name: "Build Project"
        script: "npm run build"

    artifacts:
      - build/**

    publishing:
      scripts:
        - name: "Deploy to Firebase Hosting"
          script: |
            npm install -g firebase-tools
            firebase login:ci --token $FIREBASE_TOKEN
            firebase deploy --only hosting

      email:
        recipients:
          - al-hattami@outlook.com
