workflows:
  react_build_and_deploy:
    name: "React Build and Beta Test Deploy"
    environment:
      node: "20"
      groups:
        -" beta-testers"

    scripts:
      - name: "Install Dependencies"
        script: "npm ci"
      - name: "Build Project"
        script: "npm run build"  

    artifacts:
      - build/**  

    publishing:
      scripts:
        - name: "Deploy to Firebase App Distribution"
          script: |
            export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
            firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
              --app 1:559732628127:web:845bbd360592c79895e0aa

      email:
        recipients:
          - al-hattami@outlook.com
