workflows:
  web-app-workflow:
    name: Web App Workflow
    triggers:
      - push:
          branches:
            - ci-cd-setup # Change this to your active branch if different
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Run Tests
        script: npm test
      - name: Build Project
        script: npm run build
      - name: Deploy to Firebase
        script: |
          npm install -g firebase-tools
          firebase deploy --only hosting
